#ifndef __INC_SERVICE_H__
#define __INC_SERVICE_H__

#define GF_ENABLE_MOB_PROTO



/* SECURITY IMPROVEMENT */
#define ENABLE_PORT_SECURITY

/* DEFAULT YMIR MACRO */
	#define _IMPROVED_PACKET_ENCRYPTION_
	#define __PET_SYSTEM__
	#define __UDP_BLOCK__
	
	#define LC_TEXT(str) locale_find(str)
#endif





#ifdef GF_ENABLE_MOB_PROTO
	#define GF_ENABLE_MOB_PROTO_SCALE_PCT
	#define GF_ENABLE_MOB_PROTO_RESIST_CLAW
	#define GF_ENABLE_MOB_PROTO_RESIST_BLEEDING
//	#define GF_ENABLE_MOB_PROTO_SUNG_MA
#endif



/* UNUSED YMIR MACROS

	#define __AUCTION__

#define __LIMIT_TIME__
#ifdef __LIMIT_TIME__
	#define ENABLE_LIMIT_TIME
	#define GLOBAL_LIMIT_TIME 1409996783UL // Sat Sep  6 18:46:23 2014
	#define TIME_OVER_PONG_DOWN_RATE 	50000
	#define TIME_OVER_LOGIN_DOWN_RATE 	10000
#endif

*/

